# Transportation Problem Tests

This notebook contains test cases for three transportation problem solving methods:
- North-West Corner Method (NWCM)
- Vogel's Approximation Method (VAM)
- Russell's Approximation Method

In [1]:
from src.NWCM import NWCM
from src.VAM import VAM
from src.Russel import Russel
from src.TransportationProblem import TransportationProblem
import numpy as np


In [2]:
def run_test(supply: list, demands: list, costs: list, test_num: int):
    """
    Run a test case with all three methods and display results
    """
    n = len(supply)
    m = len(demands)
    
    print(f"\n### Test Case {test_num}")
    print("\nInput Parameters:")
    print(f"Supply Vector (S): {supply}")
    print(f"Demand Vector (D): {demands}")
    print("Cost Matrix (C):")
    for row in costs:
        print(row)
    
    tp = TransportationProblem(n, m, supply, demands, costs)
    
    print("\nResults:")
    
    print("\nNorth-West Corner Method:")
    nwcm = NWCM(tp)
    nwcm_sol = nwcm.solve()
    initial = np.zeros((n, m))
    for item in nwcm_sol:
        initial[item[0]][item[1]] = item[3]
        
    print("Solution Matrix:")
    print(initial)
    
    print("\nVogel's Approximation Method:")
    tp = TransportationProblem(n, m, supply, demands, costs)
    vam = VAM(tp)
    vam_sol = vam.solve()
    initial = np.zeros((n, m))
    for item in vam_sol:
        initial[item[0]][item[1]] = item[3]
    print("Solution Matrix:")
    print(initial)
    
    print("\nRussell's Approximation Method:")
    tp = TransportationProblem(n, m, supply, demands, costs)
    russel = Russel(tp)
    russel_sol = russel.solve()
    initial = np.zeros((n, m))
    for item in russel_sol:
        initial[item[0]][item[1]] = item[3]
    print("Solution Matrix:")
    print(initial)

### Test Case 1

In [3]:
supply = [15, 20, 25]
demands = [10, 10, 20, 20]
costs = [
    
    [8, 6, 10, 9],
    [9, 12, 13, 7],
    [14, 9, 16, 5]
]

run_test(supply, demands, costs, 1)


### Test Case 1

Input Parameters:
Supply Vector (S): [15, 20, 25]
Demand Vector (D): [10, 10, 20, 20]
Cost Matrix (C):
[8, 6, 10, 9]
[9, 12, 13, 7]
[14, 9, 16, 5]

Results:

North-West Corner Method:
Solution Matrix:
[[10.  5.  0.  0.]
 [ 0.  5. 15.  0.]
 [ 0.  0.  5. 20.]]

Vogel's Approximation Method:
Solution Matrix:
[[ 0.  5. 10.  0.]
 [10.  0. 10.  0.]
 [ 0.  5.  0. 20.]]

Russell's Approximation Method:
Solution Matrix:
[[ 0.  5. 10.  0.]
 [10.  0. 10.  0.]
 [ 0.  5.  0. 20.]]


Expected outputs:
- North-West Corner Method: `[[10, 5, 0, 0], [0, 5, 15, 0], [0, 0, 5, 20]]`
- Vogel's Approximation Method: `[[0, 5, 10, 0], [10, 0, 10, 0], [0, 5, 0, 20]]`
- Russell's Approximation Method: `[[0, 5, 10, 0], [10, 0, 10, 0], [0, 5, 0, 20]]`

### Test Case 2

In [4]:
supply = [25, 15, 30]
demands = [15, 10, 25, 20]
costs = [
    [4, 8, 6, 12],
    [10, 14, 7, 11],
    [13, 6, 15, 9]
    
]

run_test(supply, demands, costs, 2)


### Test Case 2

Input Parameters:
Supply Vector (S): [25, 15, 30]
Demand Vector (D): [15, 10, 25, 20]
Cost Matrix (C):
[4, 8, 6, 12]
[10, 14, 7, 11]
[13, 6, 15, 9]

Results:

North-West Corner Method:
Solution Matrix:
[[15. 10.  0.  0.]
 [ 0.  0. 15.  0.]
 [ 0.  0. 10. 20.]]

Vogel's Approximation Method:
Solution Matrix:
[[15.  0. 10.  0.]
 [ 0.  0. 15.  0.]
 [ 0. 10.  0. 20.]]

Russell's Approximation Method:
Solution Matrix:
[[15.  0. 10.  0.]
 [ 0.  0. 15.  0.]
 [ 0. 10.  0. 20.]]


Expected outputs:
- North-West Corner Method: `[[15, 10, 0, 0] [0, 0 ,15, 0], [0,0,10,20]]`
- Vogel's Approximation Method: `[[15, 0, 10, 0],[0, 0, 15, 0],[0, 10, 0, 20]]`
- Russell's Approximation Method: `[[15, 0, 10, 0], [0, 0, 15, 0], [0,10,0,20]]`

### Test Case 3

In [5]:
supply = [30, 25, 15]
demands = [20, 10, 15, 25]
costs = [
    [5, 9, 12, 8],
    [6, 11, 14, 10],
    [15, 13, 10, 7]
]

run_test(supply, demands, costs, 3)


### Test Case 3

Input Parameters:
Supply Vector (S): [30, 25, 15]
Demand Vector (D): [20, 10, 15, 25]
Cost Matrix (C):
[5, 9, 12, 8]
[6, 11, 14, 10]
[15, 13, 10, 7]

Results:

North-West Corner Method:
Solution Matrix:
[[20. 10.  0.  0.]
 [ 0.  0. 15. 10.]
 [ 0.  0.  0. 15.]]

Vogel's Approximation Method:
Solution Matrix:
[[ 0. 10. 10. 10.]
 [20.  0.  5.  0.]
 [ 0.  0.  0. 15.]]

Russell's Approximation Method:
Solution Matrix:
[[ 0. 10.  0. 20.]
 [20.  0.  0.  5.]
 [ 0.  0. 15.  0.]]


Expected outputs:
- North-West Corner Method: `[[20, 10, 0, 0] [0, 0 ,15, 10], [0, 0, 0, 15]]`
- Vogel's Approximation Method: `[[0, 10, 10, 10],[20, 0, 5, 0],[0, 0, 0, 15]]`
- Russell's Approximation Method: `[[0, 10, 0, 20], [20, 0, 0, 5], [0, 0, 15, 0]]`